{
 "title": "Individual Flows",
 "tags": [ "netsage" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "flow_type",
    "label": "Flow Type",
    "query": "{\"find\":\"terms\", \"field\":\"meta.flow_type.keyword\"}"
   },
   {
    "name": "src",
    "label": "Source Organization",
    "query": "{\"find\":\"terms\", \"field\":\"meta.src_organization.keyword\", \"query\": \"meta.flow_type:$flow_type\", \"size\": 100000} "
   },
   {
    "name": "dest",
    "label": "Destination Organization",
    "query": "{\"find\":\"terms\", \"field\":\"meta.dst_organization.keyword\", \"query\": \"meta.flow_type:$flow_type\", \"size\": 100000}"
   },
   {
    "name": "sensor",
    "label": "Sensor",
    "query": "{\"find\":\"terms\", \"field\":\"meta.sensor_id.keyword\", \"query\":\"meta.flow_type:$flow_type\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "netsagenavigation",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "content": "<!-- Global site tag (gtag.js) - Google Analytics -->\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-142763676-1\"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag('js', new Date());\n\n  gtag('config', 'UA-142763676-1');\n</script>\n<h1><center><b>Individual Flow Dashboard</b></center></h1>\n<center>This dashboard shows per-flow level data, given a particular source and destination organization. \nThe table shows the volume, rate, retransmits, retransmit %, RTT and duration for each flow. </center>\n<center>The heatmaps below show volume, rate and retransmits of flows for the given source and destination organizations over a specific period of time.</center>\n<center>The horizontal axis represents days and the vertical axis represents time of day. Darker squares show higher data transmissions at those hours.</center>\n<center><b>Please note that retransmit and RTT information is only available for tstat flow data, and a maximum of 10,000 results are shown in the tables.</b></center>\n"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 1, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "meta.id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest  AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 5 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest  AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 5 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.tcp_rexmit_pkts",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "3" },
        { "name": "var2", "pipelineAgg": "4" }
       ],
       "settings": { "script": "params.var1 / params.var2" },
       "type": "bucket_script"
      },
      {
       "field": "values.tcp_rexmit_pkts",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "values.num_packets",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.tcp_rtt_avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Flows from Source to Destination",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "_id",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10000" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "start",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "end",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.src_organization.keyword",
       "id": "28",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.src_ip.keyword",
       "id": "32",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.dst_organization.keyword",
       "id": "33",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.dst_ip.keyword",
       "id": "31",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "12",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "field": "values.bits_per_second",
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.bits_per_second",
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "values.tcp_rexmit_pkts",
       "id": "21",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "24",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "21" },
        { "name": "var2", "pipelineAgg": "25" }
       ],
       "settings": { "script": "params.var1 / params.var2" },
       "type": "bucket_script"
      },
      {
       "field": "values.num_packets",
       "id": "25",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.tcp_rtt_min",
       "id": "26",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.duration",
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Retransmits",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.tcp_rexmit_pkts",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 },
   "content": "<h1 style=\"margin-top:20px;\"><center>Summary Statistics</center></h1>"
  },
  {
   "title": "Top Protocols",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.protocol.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.src_organization.keyword:$src AND meta.dst_organization.keyword:$dest AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 },
   "content": "<center style=\"margin-top:20px;\"><h1>Reverse Direction</h1></center>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 1, "y": 69 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "meta.id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "meta.src_organization.keyword:$dest AND meta.dst_organization.keyword:$src  AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 69 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization.keyword:$dest AND meta.dst_organization.keyword:$src  AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 69 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization.keyword:$dest AND meta.dst_organization.keyword:$src AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 69 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.tcp_rexmit_pkts",
       "id": "1",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "3" },
        { "name": "var2", "pipelineAgg": "4" }
       ],
       "settings": { "script": "params.var1 / params.var2" },
       "type": "bucket_script"
      },
      {
       "field": "values.tcp_rexmit_pkts",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "values.num_packets",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.src_organization.keyword:$dest AND meta.dst_organization.keyword:$src AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 69 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.tcp_rtt_avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization.keyword:$dest AND meta.dst_organization.keyword:$src AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Flows from Source to Destination (Reverse)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.id.keyword",
       "id": "15",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "start",
       "id": "16",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "end",
       "id": "17",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.src_organization.keyword",
       "id": "28",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.src_ip.keyword",
       "id": "32",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.dst_organization.keyword",
       "id": "33",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "meta.dst_ip.keyword",
       "id": "31",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "12",
       "inlineScript": "_value / 8",
       "meta": {},
       "settings": { "script": { "inline": "_value / 8" } },
       "type": "sum"
      },
      {
       "field": "values.bits_per_second",
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.bits_per_second",
       "id": "30",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "values.tcp_rexmit_pkts",
       "id": "21",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      },
      {
       "field": "select field",
       "id": "24",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "21" },
        { "name": "var2", "pipelineAgg": "25" }
       ],
       "settings": { "script": "params.var1 / params.var2" },
       "type": "bucket_script"
      },
      {
       "field": "values.num_packets",
       "id": "25",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.tcp_rtt_min",
       "id": "26",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "values.duration",
       "id": "27",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization.keyword:$destAND meta.dst_organization.keyword:$src AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Volume (Reverse)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.num_bits",
       "id": "1",
       "inlineScript": "_value/8",
       "meta": {},
       "settings": { "script": { "inline": "_value/8" } },
       "type": "sum"
      }
     ],
     "query": "meta.src_organization.keyword:$destAND meta.dst_organization.keyword:$src AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Rate (Reverse)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.bits_per_second",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "meta.src_organization.keyword:$dest AND meta.dst_organization.keyword:$src AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "By Retransmits (Reverse)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "values.tcp_rexmit_pkts",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "meta.src_organization.keyword:$dest AND meta.dst_organization.keyword:$src AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 120 },
   "content": "<h1 style=\"margin-top:20px;\"><center> Reverse Summary Statistics</center></h1>"
  },
  {
   "title": "Top Protocols",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.protocol.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.src_organization.keyword:$dest AND meta.dst_organization.keyword:$src AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Source Ports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 122 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.src_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.src_organization.keyword:$dest AND meta.dst_organization.keyword:$src AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  {
   "title": "Top Destination Ports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 122 },
   "yaxes": [
    { "format": "short", "label": "Number of Flows" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "meta.dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      { "field": "start", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.src_organization.keyword:$dest AND meta.dst_organization.keyword:$src AND meta.sensor_id.keyword:$sensor AND meta.flow_type.keyword:$flow_type",
     "timeField": "start"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 131 },
   "content": "<div> If you have any questions, concerns, or other issues, feel free to contact us at <a>netsage@iu.edu. </a> Thanks!  <img style=\"margin-left:10px\" src=\"https://www.nsf.gov/images/logos/NSF_4-Color_bitmap_Logo.png\" width=50 height=50> <a href=\"https://www.nsf.gov/awardsearch/showAward?AWD_ID=1540933\"> NSF GRANT 1540933 </a> </img> <span style=\"float:right; position:relative; top:8px\"> To Review the NetSage Data Policy <a href=\"http://www.netsage.global/home/netsage-privacy-policy\"> click here </a> </div>"
  }
 ]
}